# Be sure to restart your server when you modify this file.

# order Groove for auto delivery

default: &default
   og_tag_url_development           :   https://staging.static.ordergroove.com
   og_tag_url_production        :   https://static.ordergroove.com
   og_subscription_url_development  :   https://staging.sc.ordergroove.com/subscription/create
   og_subscription_url_production : https://sc.ordergroove.com/subscription/create
   og_bulkdiscount_url_development  :   https://staging.v2.ordergroove.com/utilities/html/
   og_bulkdiscount_url_production : https://api.ordergroove.com/utilities/html/

   og_ftp_host_production   :   feeds.ordergroove.com
   og_ftp_host_development      :   staging.feeds.ordergroove.com
   og_ftp_passive           :   1

store1:
   <<: *default
   og_merchant_id           :   your_merchagne_id
   og_hashkey               :   your_hashkey
   og_ftp_user              :   your_ftp_user
   og_ftp_pass              :   your_ftp_passworkd

pwb:
   <<: *default
   og_merchant_id           :   your_merchagne_id
   og_hashkey               :   your_hashkey
   og_ftp_user              :   your_ftp_user
   og_ftp_pass              :   your_ftp_passworkd
he:
   <<: *default
   og_merchant_id           :   your_merchagne_id
   og_hashkey               :   your_hashkey
   og_ftp_user              :   your_ftp_user
   og_ftp_pass              :   your_ftp_passworkd
